from tkinter import *
window=Tk()
window.title('Шифрование')
window.geometry('350x500')
choice=StringVar()
frame0=LabelFrame(text='Выбор шифра',height=100)
radiocaesar=Radiobutton(frame0,text='Шифр Цезаря',variable=choice,
                        value='Цезарь',indicatoron=0)
radioatbash=Radiobutton(frame0,text='Шифр Атбаш',variable=choice,
                        value='Атбаш',indicatoron=0)
frame1=LabelFrame(text='Данные',height=100)
label1=Label(frame1,text='Введите текст:')
label2=Label(frame1,text='Введите ключ:')
plaintextbox=Entry(frame1,width=25)
keybox=Entry(frame1,width=10)
frame2=LabelFrame(text='Зашифрованные сообщения',height=100)
ciphername=Label(frame2,text='Шифр Цезаря:')
ciphermessage=Label(frame2)
button=Button(text='Зашифровать')
frame0.pack(fill=X,padx=10,pady=10)
radiocaesar.pack(padx=10,pady=10)
radioatbash.pack(padx=10,pady=10)
frame1.pack(fill=X,padx=10,pady=10)
label1.grid(column=0,row=0,padx=10,pady=10)
label2.grid(column=1,row=0,padx=10,pady=10)
keybox.grid(column=1,row=1,padx=10,pady=10)
plaintextbox.grid(column=0,row=1,padx=10,pady=10)
frame2.pack(fill=X,padx=10,pady=10)
ciphername.pack(padx=10,pady=10)
ciphermessage.pack(padx=10,pady=10)
button.pack(padx=10,pady=10)
if __name__=='__main__':
    window.mainloop()
